### ISSUE TITLE
credit for reviewers

### ISSUE THREAD

**Issue by lheagy** [minrk/ghpro#11]
@mpacer, @willingc and I were chatting about also giving credit in a release to contributors who are reviewers (it is a time-consuming contributions, but isn't counted in the github contributions). 

Would it be possible to also look at who reviewed and commented on the pull requests that contribute to a release and acknowledge those in release notes?

**Comment by minrk** [comment]
That would be super cool. It should be possible by adding to [get_authors](https://github.com/minrk/ghpro/blob/master/ghpro/api.py#L229) an iteration through `comments_url` similar to what we already do with `commits_url`.

https://github.com/minrk/ghpro/blob/46763fec7ad85c20dc61474a9a6dbff6ec088236/ghpro/api.py#L226-L236

**Comment by minrk** [comment]
closed by #21
