### ISSUE TITLE
No version number attached to ghpro…

### ISSUE THREAD

**Issue by mpacer** [minrk/ghpro#15]
How are ghpro's version numbers currently being assigned? 

I thought they were required… but when I install editably it's producing ghpro-1.1.2.dev19 but I can't figure out how or where….

**Comment by mpacer** [comment]
I'm gathering this somehow relates to `pbr` but I can't figure out how… could a note about that be included somewhere?

**Comment by minrk** [comment]
It's derived from the git tag.
