### ISSUE TITLE
Use cherry-pick instead of apply-patch ?

### ISSUE THREAD

**Issue by Carreau** [minrk/ghpro#2]
@tacaswell asked  me a few hours ago why we would use `apply` and  that one could use `git cherry-pick -m 1 SHAOFTHEMERGE` to backport and that he thinks "it lets git do more of the work for you".

I think it's probably cleaner as well.

**Comment by tacaswell** [comment]
Sorry for being slow creating the issue!

**Comment by Carreau** [comment]
> Sorry for being slow creating the issue!

No problem,  I'm sure you have plenty of things to do with MPL.

**Comment by minrk** [comment]
Worth a shot! We'd have to make sure we fetch the ref first, but that's easy enough.

**Comment by minrk** [comment]
Simpler and better, thanks!
